### ISSUE TITLE
 1.24.0-dev.4.2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stack_trace#27]
When an pkg/http connection fails I get this stack – with pubviz

Not sure if this is an SDK issue or stack_trace.

I'm on SDK 
```
HandshakeException: Connection terminated during handshake
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      new Timer (dart:async/timer.dart:52)
unparsed       #6      Timer.run (dart:async/timer.dart:90)
unparsed       #7      new Future (dart:async/future.dart:156)
unparsed       #8      _HttpClient._getConnection (dart:io/http_impl.dart:1910)
unparsed       #9      _HttpClient._openUrl (dart:io/http_impl.dart:1813)
unparsed       #10     _HttpClient.openUrl (dart:io/http_impl.dart:1718)
unparsed       #11     IOClient.send (package:http/src/io_client.dart:43)
<asynchronous  suspension>
unparsed       #12     BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
<asynchronous  suspension>
unparsed       #13     BaseClient.get (package:http/src/base_client.dart:34)
unparsed       #14     get.<anonymous closure> (package:http/http.dart:47)
unparsed       #15     _withClient (package:http/http.dart:167)
<asynchronous  suspension>
unparsed       #16     get (package:http/http.dart:47)
unparsed       #17     getLatestVersion (package:pubviz/src/util.dart:9)
<asynchronous  suspension>
unparsed       #18     VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86)
<asynchronous  suspension>
unparsed       #19     VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #20     _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #21     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #22     Future.wait (dart:async/future.dart:355)
unparsed       #23     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #24     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #25     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #26     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #27     _rootRun (dart:async/zone.dart:1120)
unparsed       #28     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #29     runZoned (dart:async/zone.dart:1467)
unparsed       #30     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #31     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      IOClient.send (package:http/src/io_client.dart:39)
unparsed       #8      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
<asynchronous  suspension>
unparsed       #9      BaseClient.get (package:http/src/base_client.dart:34)
unparsed       #10     get.<anonymous closure> (package:http/http.dart:47)
unparsed       #11     _withClient (package:http/http.dart:167)
<asynchronous  suspension>
unparsed       #12     get (package:http/http.dart:47)
unparsed       #13     getLatestVersion (package:pubviz/src/util.dart:9)
<asynchronous  suspension>
unparsed       #14     VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86)
<asynchronous  suspension>
unparsed       #15     VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #16     _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #17     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #18     Future.wait (dart:async/future.dart:355)
unparsed       #19     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #20     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #21     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #22     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #23     _rootRun (dart:async/zone.dart:1120)
unparsed       #24     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #25     runZoned (dart:async/zone.dart:1467)
unparsed       #26     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #27     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      BaseClient._sendUnstreamed (package:http/src/base_client.dart:152)
unparsed       #8      BaseClient.get (package:http/src/base_client.dart:34)
unparsed       #9      get.<anonymous closure> (package:http/http.dart:47)
unparsed       #10     _withClient (package:http/http.dart:167)
<asynchronous  suspension>
unparsed       #11     get (package:http/http.dart:47)
unparsed       #12     getLatestVersion (package:pubviz/src/util.dart:9)
<asynchronous  suspension>
unparsed       #13     VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86)
<asynchronous  suspension>
unparsed       #14     VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #15     _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #16     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #17     Future.wait (dart:async/future.dart:355)
unparsed       #18     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #19     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #20     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #21     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #22     _rootRun (dart:async/zone.dart:1120)
unparsed       #23     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #24     runZoned (dart:async/zone.dart:1467)
unparsed       #25     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #26     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      _withClient (package:http/http.dart:164)
unparsed       #8      get (package:http/http.dart:47)
unparsed       #9      getLatestVersion (package:pubviz/src/util.dart:9)
<asynchronous  suspension>
unparsed       #10     VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86)
<asynchronous  suspension>
unparsed       #11     VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #12     _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #13     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #14     Future.wait (dart:async/future.dart:355)
unparsed       #15     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #16     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #17     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #18     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #19     _rootRun (dart:async/zone.dart:1120)
unparsed       #20     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #21     runZoned (dart:async/zone.dart:1467)
unparsed       #22     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #23     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      getLatestVersion (package:pubviz/src/util.dart:7)
unparsed       #8      VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86)
<asynchronous  suspension>
unparsed       #9      VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #10     _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #11     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #12     Future.wait (dart:async/future.dart:355)
unparsed       #13     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #14     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #15     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #16     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #17     _rootRun (dart:async/zone.dart:1120)
unparsed       #18     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #19     runZoned (dart:async/zone.dart:1467)
unparsed       #20     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #21     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:83)
unparsed       #8      VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58)
<asynchronous  suspension>
unparsed       #9      _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #10     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #11     Future.wait (dart:async/future.dart:355)
unparsed       #12     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #13     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #14     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #15     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #16     _rootRun (dart:async/zone.dart:1120)
unparsed       #17     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #18     runZoned (dart:async/zone.dart:1467)
unparsed       #19     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #20     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1045)
unparsed       #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:30)
unparsed       #5      VizPackage.forDirectory (package:pubviz/src/viz_package.dart:38)
unparsed       #6      _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119)
<asynchronous  suspension>
unparsed       #7      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #8      Future.wait (dart:async/future.dart:355)
unparsed       #9      _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #10     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #11     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #12     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #13     _rootRun (dart:async/zone.dart:1120)
unparsed       #14     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #15     runZoned (dart:async/zone.dart:1467)
unparsed       #16     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #17     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:117)
unparsed       #8      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
unparsed       #9      Future.wait (dart:async/future.dart:355)
unparsed       #10     _getReferencedPackages (package:pubviz/src/viz_root.dart:127)
<asynchronous  suspension>
unparsed       #11     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #12     main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #13     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #14     _rootRun (dart:async/zone.dart:1120)
unparsed       #15     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #16     runZoned (dart:async/zone.dart:1467)
unparsed       #17     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #18     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1045)
unparsed       #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:30)
unparsed       #5      _getReferencedPackages (package:pubviz/src/viz_root.dart:112)
unparsed       #6      VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25)
<asynchronous  suspension>
unparsed       #7      main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #8      Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #9      _rootRun (dart:async/zone.dart:1120)
unparsed       #10     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #11     runZoned (dart:async/zone.dart:1467)
unparsed       #12     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #13     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerUnaryCallback (dart:async/zone.dart:1045)
unparsed       #4      _asyncThenWrapperHelper (dart:async-patch/async_patch.dart:30)
unparsed       #5      VizRoot.forDirectory (package:pubviz/src/viz_root.dart:23)
unparsed       #6      main.<anonymous closure> (http://localhost:57487/pubviz.dart:40)
<asynchronous  suspension>
unparsed       #7      Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #8      _rootRun (dart:async/zone.dart:1120)
unparsed       #9      _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #10     runZoned (dart:async/zone.dart:1467)
unparsed       #11     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #12     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
===== asynchronous gap ===========================
unparsed       #3      _CustomZone.registerCallback (dart:async/zone.dart:1034)
unparsed       #4      _CustomZone.bindCallback (dart:async/zone.dart:924)
unparsed       #5      scheduleMicrotask (dart:async/schedule_microtask.dart:148)
unparsed       #6      new Future.microtask (dart:async/future.dart:182)
unparsed       #7      main.<anonymous closure> (http://localhost:57487/pubviz.dart:39)
unparsed       #8      Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:92)
unparsed       #9      _rootRun (dart:async/zone.dart:1120)
unparsed       #10     _CustomZone.run (dart:async/zone.dart:1001)
unparsed       #11     runZoned (dart:async/zone.dart:1467)
unparsed       #12     Chain.capture (package:stack_trace/src/chain.dart:90)
unparsed       #13     main (http://localhost:57487/pubviz.dart:39)
<asynchronous  suspension>
unparsed       #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
unparsed       #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by kevmoo** [comment]
This only happens when I run via `pub global activate`. When I run it directly, the stack is fine.

**Comment by kevmoo** [comment]
Here's the output w/out Chain.track

```
#0      IOClient.send (package:http/src/io_client.dart:30:23)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
<asynchronous suspension>
#2      BaseClient.get (package:http/src/base_client.dart:34:5)
#3      get.<anonymous closure> (package:http/http.dart:47:34)
#4      _withClient (package:http/http.dart:167:20)
<asynchronous suspension>
#5      get (package:http/http.dart:47:3)
#6      getLatestVersion (package:pubviz/src/util.dart:9:24)
<asynchronous suspension>
#7      VizPackage.updateLatestVersion (package:pubviz/src/viz_package.dart:86:28)
<asynchronous suspension>
#8      VizPackage.forDirectory (package:pubviz/src/viz_package.dart:58:21)
<asynchronous suspension>
#9      _getReferencedPackages.<anonymous closure> (package:pubviz/src/viz_root.dart:119:31)
<asynchronous suspension>
#10     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#11     Future.wait (dart:async/future.dart:355)
#12     _getReferencedPackages (package:pubviz/src/viz_root.dart:127:16)
<asynchronous suspension>
#13     VizRoot.forDirectory (package:pubviz/src/viz_root.dart:25:26)
<asynchronous suspension>
#14     main (http://localhost:59410/pubviz.dart:39:28)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by nex3** [comment]
What version of `stack_trace` are you using?

**Comment by kevmoo** [comment]
`1.7.3`

**Comment by nex3** [comment]
Are you sure? `stack_trace` has supported this stack trace format since 1.7.1. Is it possible that your globally-activated executable is using an old version?

**Comment by kevmoo** [comment]
I'm using `pub global activate --source path .` from the pubviz path.

pubspec.lock has `stack_trace 1.7.3`

**Comment by nex3** [comment]
And the behavior is different depending on whether or not you use `pub global run`?

How exactly are you invoking `stack_trace`?

**Comment by kevmoo** [comment]
https://github.com/kevmoo/pubviz/blob/master/bin/pubviz.dart#L39

**Comment by nex3** [comment]
I'm trying to reproduce this locally... is there some way I can do that without relying on a transient HTTP issue?

**Comment by kevmoo** [comment]
If you're sync'd down pubviz, you could change the domain in the URL to garbage – likely?

**Comment by kevmoo** [comment]
...or unplug your network cable

**Comment by nex3** [comment]
I don't know what "the domain in the URL" refers to. Can you give me a patch I can apply?

**Comment by natebosch** [comment]
Assuming this has been fixed. We can reopen if it pops back up.
