### ISSUE TITLE
better handling empty stack traces

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stack_trace#4]
These are causing crashes with the integration of test and scheduled_test

**Comment by kevmoo** [comment]
```
Uncaught Error: FormatException: Couldn't parse package:stack_trace stack trace line ''.
Stack Trace:
#0      Frame.Frame.parseFriendly (package:stack_trace/src/frame.dart:253:7)
#1      Trace.Trace.parseFriendly.<anonymous closure> (package:stack_trace/src/trace.dart:194:30)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:376)
#3      List.List.from (dart:core-patch/array_patch.dart:44)
#4      Iterable.toList (dart:core/iterable.dart:340)
#5      Trace.Trace (package:stack_trace/src/trace.dart:198:57)
#6      Trace.Trace.parseFriendly (package:stack_trace/src/trace.dart:191:9)
#7      Chain.Chain.parse.<anonymous closure> (package:stack_trace/src/chain.dart:131:52)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:398)
#9      ListIterable.toList (dart:_internal/iterable.dart:205)
#10     Chain.Chain (package:stack_trace/src/chain.dart:135:57)
#11     Chain.Chain.parse (package:stack_trace/src/chain.dart:131:9)
#12     RemoteException.deserialize (package:test/src/util/remote_exception.dart:73:13)
#13     IsolateTest.load.<anonymous closure>.<anonymous closure> (package:test/src/runner/vm/isolate_test.dart:53:44)
```

**Comment by kevmoo** [comment]
Note: this *crashes* the test runner. It'd be nice (maybe?) if this resulted in just a test failure *or* if these types of issues were captures w/ Chain.capture and reported w/ a request for a bug report, etc...
